"""Pre-aggregate the sports breakdown for the static GitHub Pages site.

GitHub Pages is static (no Python at request time), so we compute the by-sport,
by-day breakdown here and emit:
  * docs/data.js   -> `window.DKEX_DATA = {...}` (loaded by the page, no fetch/CORS)
  * docs/dkex_sports_breakdown.csv -> a committed, directly-downloadable CSV

Run:  PYTHONPATH=src python scripts/build_site_data.py
"""

from __future__ import annotations

import json
import os
import sqlite3
from datetime import date

from dkex import DEFAULT_DB
from dkex.reference import LEAGUE_NAMES

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")

MEASURES = {  # key -> (sql column, human label, is_dollars)
    "contracts": ("trade_volume", "Contracts traded", False),
    "notional": ("notional_at_price", "Notional @ price ($, est.)", True),
    "max_notional": ("max_notional", "Max notional ($, est.)", True),
}


def main(db_path: str = DEFAULT_DB):
    if not os.path.exists(db_path):
        raise SystemExit(f"No DB at {db_path}. Run `python -m dkex.load` first.")
    conn = sqlite3.connect(db_path)
    rows = conn.execute(
        "SELECT business_date, league_raw, "
        "       SUM(trade_volume)      AS contracts, "
        "       SUM(notional_at_price) AS notional, "
        "       SUM(max_notional)      AS max_notional "
        "FROM decoded_reports "
        "GROUP BY business_date, league_raw "
        "ORDER BY business_date, league_raw").fetchall()
    dates = sorted({r[0] for r in rows})
    # Fixed league order (baseball first, then golf), only those present.
    present = {r[1] for r in rows}
    order = [lg for lg in ("MLB", "KBO", "NPB", "PGA") if lg in present]
    order += sorted(present - set(order))

    data_rows = [{
        "date": r[0], "league": r[1],
        "contracts": int(r[2] or 0),
        "notional": round(float(r[3] or 0.0), 2),
        "max_notional": round(float(r[4] or 0.0), 2),
    } for r in rows]

    payload = {
        "generated": date.today().isoformat(),
        "coverage": [dates[0], dates[-1]] if dates else [],
        "dates": dates,
        "leagues": order,
        "leagueNames": {lg: LEAGUE_NAMES.get(lg, lg) for lg in order},
        "measures": {k: {"label": v[1], "dollars": v[2]} for k, v in MEASURES.items()},
        "rows": data_rows,
    }

    os.makedirs(DOCS, exist_ok=True)
    with open(os.path.join(DOCS, "data.js"), "w") as f:
        f.write("// Auto-generated by scripts/build_site_data.py — do not edit.\n")
        f.write("window.DKEX_DATA = ")
        json.dump(payload, f, separators=(",", ":"))
        f.write(";\n")

    # Also a plain CSV file for a no-JS direct download.
    csv_path = os.path.join(DOCS, "dkex_sports_breakdown.csv")
    with open(csv_path, "w") as f:
        f.write("date,league,contracts_traded,notional_at_price_usd_est,"
                "max_notional_usd_est\n")
        for r in data_rows:
            f.write(f"{r['date']},{r['league']},{r['contracts']},"
                    f"{r['notional']},{r['max_notional']}\n")

    conn.close()
    print(f"[build-site] {len(data_rows)} rows · {len(dates)} dates · "
          f"leagues {order}")
    print(f"[build-site] wrote docs/data.js and docs/dkex_sports_breakdown.csv")


if __name__ == "__main__":
    main()
